replicaCount: 1

namespace: minikube
env: minikube

rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

service:
  port: 8090
  type: ClusterIP

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 256Mi

email:
  secret:
    key: aardvark
  token:
    salt: aardvark