version: '2'

services:
  db:
    container_name: postgres
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  party-service:
    container_name: party-service
    build: ./
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - "8081:8081"