version: '2'

services:
  db:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: partysvc
    image: postgres:9.6
    ports:
      - "5432:5432"

