# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class EnrolmentCode(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, code: str=None):
        """
        EnrolmentCode - a model defined in Swagger

        :param code: The code of this EnrolmentCode.
        :type code: str
        """
        self.swagger_types = {
            'code': str
        }

        self.attribute_map = {
            'code': 'code'
        }

        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'EnrolmentCode':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The enrolmentCode of this EnrolmentCode.
        :rtype: EnrolmentCode
        """
        return deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """
        Gets the code of this EnrolmentCode.

        :return: The code of this EnrolmentCode.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """
        Sets the code of this EnrolmentCode.

        :param code: The code of this EnrolmentCode.
        :type code: str
        """

        self._code = code

