# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Error(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, logref: str=None, message: str=None):
        """
        Error - a model defined in Swagger

        :param logref: The logref of this Error.
        :type logref: str
        :param message: The message of this Error.
        :type message: str
        """
        self.swagger_types = {
            'logref': str,
            'message': str
        }

        self.attribute_map = {
            'logref': 'logref',
            'message': 'message'
        }

        self._logref = logref
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error of this Error.
        :rtype: Error
        """
        return deserialize_model(dikt, cls)

    @property
    def logref(self) -> str:
        """
        Gets the logref of this Error.
        A unique identifier generated per error

        :return: The logref of this Error.
        :rtype: str
        """
        return self._logref

    @logref.setter
    def logref(self, logref: str):
        """
        Sets the logref of this Error.
        A unique identifier generated per error

        :param logref: The logref of this Error.
        :type logref: str
        """

        self._logref = logref

    @property
    def message(self) -> str:
        """
        Gets the message of this Error.
        Description of the error that occurred

        :return: The message of this Error.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this Error.
        Description of the error that occurred

        :param message: The message of this Error.
        :type message: str
        """

        self._message = message

