apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.crons.markForDeletionScheduler.name }}
spec:
  suspend: true
  schedule: "{{ .Values.crons.markForDeletionScheduler.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.crons.markForDeletionScheduler.name }}
            image: radial/busyboxplus:curl
            env:
            - name: SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: security-credentials
                  key: security-user
            - name: SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: security-credentials
                  key: security-password
            - name: TARGET
              value: {{ .Values.crons.markForDeletionScheduler.target }}
            args:
            - /bin/sh
            - -c
            - curl -u $(SECURITY_USER_NAME):$(SECURITY_USER_PASSWORD) -X DELETE http://$(PARTY_SERVICE_HOST):$(PARTY_SERVICE_PORT)/$(TARGET)
          restartPolicy: OnFailure
