apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  data:
  - secretKey: email-secret-key
    remoteRef:
      key: {{ .Chart.Name }}
      property: email-secret-key
      version: latest
  - secretKey: email-token-salt
    remoteRef:
      key: {{ .Chart.Name }}
      property: email-token-salt
      version: latest