apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: party
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  refreshInterval: 1m
  data:
  - secretKey: email-secret-key
    remoteRef:
      key: party
      property: email-secret-key
      version: latest
  - secretKey: email-token-salt
    remoteRef:
      key: party
      property: email-token-salt
      version: latest