apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: {{ .Chart.Name }}      # name of the GCP secret
      name: email-secret-key      # key name in the k8s secret
      version: latest             # version of the GCP secret
      property: email-secret-key  # json property in the GCP secret
    - key: {{ .Chart.Name }}
      name: email-token-salt
      version: latest
      property: email-token-salt