apiVersion: v1
kind: ConfigMap
metadata:
  name: ras-party-config
data:
  .env: |-
    DATABASE_URI=postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)
    RAS_OAUTH_SERVICE_PORT=$(OAUTH_PORT)
    RAS_OAUTH_CLIENT_ID=$(OAUTH_CLIENT_ID)
    RAS_OAUTH_CLIENT_SECRET=$(OAUTH_CLIENT_SECRET)
    RAS_CASE_SERVICE_HOST=$(CASE_SERVICE_HOST)
    RAS_COLLEX_SERVICE_HOST=$(COLLEX_SERVICE_HOST)
    RAS_SURVEY_SERVICE_HOST=$(SURVEY_SERVICE_HOST)
    RAS_IAC_SERVICE_HOST=$(IAC_HOST)
    RAS_OAUTH_SERVICE_HOST=$(OAUTH_HOST)
    SECURITY_USER_NAME=$(SECURITY_USER_NAME)
    SECURITY_USER_PASSWORD=$(SECURITY_USER_PASSWORD)
    ZIPKIN_DSN=http://$(ZIPKIN_SERVICE_HOST):$(ZIPKIN_SERVICE_PORT)/api/v1/spans
    ZIPKIN_SAMPLE_RATE=100
