# This Config file defines default environment variables for the different services and micro services the party
# service depends on. The common developer settings are maintained here:
# https://digitaleq.atlassian.net/wiki/display/RASB/Developer+Environment+Port+Mappings

# Individual settings defined here may be overridden via environment variables.
# To provide env var overrides, the naming either follows the names given in the 'service' section of the config,
# or for items which are related to dependencies, the name is <dependency-name.key>, for example:
# `export case-service.port=5000`

# When running on CloudFoundry, relevant values are automatically overridden via VCAP_SERVICES. Note that the name
# of the dependency must match the name of the CF service instance. E.g. for ras-party-db, there must be a
# service binding with the name 'ras-party-db'.

# The features section of the config file is intended for feature-flagging.

# When loading this config file via Flask app.config.from_yaml, the config is injected into the Flask config
# and exposed in the usual way. Dependencies are exposed via current_app.config.dependency, and features are
# similarly exposed via current_app.config.feature. E.g. to get the ras-party-db uri:

# db_uri = current_app.config.dependency['ras-party-db'].uri

service:
    NAME: ras-party
    VERSION: 1.0.0
    SCHEME: http
    HOST: 0.0.0.0
    PORT: 8081
    DEBUG: False
    LOG_LEVEL: debug
    SECRET_KEY: aardvark
    EMAIL_TOKEN_SALT: aardvark
    PARTY_SCHEMA: ras_party/schemas/party_schema.json
    SECURITY_USER_NAME: dummy_user
    SECURITY_USER_PASSWORD: dummy_password
    SECURITY_REALM: sdc
    REQUESTS_GET_TIMEOUT: 20
    REQUESTS_POST_TIMEOUT: 20

dependencies:
    ras-party-db:
        schema: partysvc
        uri: "postgres://postgres:postgres@localhost:5432/postgres"
    public-website:
        scheme: http
        host: dummy.ons.gov.uk
        port: 80
    case-service:
        scheme: http
        host: localhost
        port: 8171
    collectionexercise-service:
        scheme: http
        host: localhost
        port: 8145
    survey-service:
        scheme: http
        host: localhost
        port: 8080
    notify-service:
        url: "http://notify-gateway-service/emails/"
        email_verification_template: email_verification_id
        request_password_change_template: request_password_change_id
        confirm_password_change_template: confirm_password_change_id
    api-gateway:
        scheme: http
        host: localhost
        port: 8083
    iac-service:
        scheme: http
        host: localhost
        port: 8121
    oauth2-service:
        scheme: http
        host: localhost
        port: 8040
        client_id: "ons@ons.gov"
        client_secret: "password"


features:
    report_dependencies: false
    send_email_to_gov_notify: false
