
service:
    name: ras-party-v2
    version: 0.0.1
    scheme: http
    host: 0.0.0.0
    port: 8001

dependencies:
    ras-party-db:
        service: rds
        plan: shared-psql
        schema: ras-party
        uri: "sqlite:///ras-party"
    case-service:
        scheme: http
        host: localhost
        port: 8171
    api-gateway:
        scheme: http
        host: localhost
        port: 8000

features:
    gateway-registration: False
